app/controllers/ShopcartController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\cms\modules\catalog\api\Catalog;
use yii\cms\modules\shopcart\api\Shopcart;
use yii\web\NotFoundHttpException;


class ShopcartController extends Controller{
    
    
    public function actionIndex($action = null){
        $model_update = new \app\models\shopcart\ShopcartUpdate();
        $model_payment = new \app\models\shopcart\ShopcartPayment();
        $model_invoice = new \app\models\shopcart\ShopcartInvoice();
        $model_reserve = new \app\models\shopcart\ShopcartReserve();
        
        switch($action){
            case 'update' : $active_model = $model_update;
                break;
            case 'payment' : $active_model = $model_payment;
                break;
            case 'invoice' : $active_model = $model_invoice;
                break;
            case 'reserve' : $active_model = $model_reserve;
                break;
            default : $active_model = null;
                break;
        }
        
        if($active_model){
            if($active_model->load(Yii::$app->request->post())){
                $redirect = $active_model->action();
                if($redirect){
                    return $redirect;
                }
            }
        }
        
        return $this->render('index', [
            'goods' => Shopcart::goods(),
            'model_update' => $model_update,
            'model_payment' => $model_payment,
            'model_invoice' => $model_invoice,
            'model_reserve' => $model_reserve,
        ]);
    }
    
    
    public function actionAdd(){
        $post = Yii::$app->request->post();
        
        $item = Catalog::get($post['id']);
        if(!$item){
            throw new NotFoundHttpException('Item not found');
        }
        
        Shopcart::add($item->id, $post['count']);
        $add_message = 'Товар добавлен в корзину';
        
        if(Yii::$app->request->isAjax){
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return [
                'add_message' => $add_message,
                'goods_count' => count(Shopcart::goods()),
            ];
        }
        
        Yii::$app->getSession()->setFlash('add_message', $add_message);
        return $this->redirect(['/shopcart']);
    }
    
    
    public function actionRemove($id){
        Shopcart::remove($id);
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    
    public function actionOrder($id, $token){
        $order = Shopcart::order($id);
        if(!$order || $order->access_token != $token){
            throw new NotFoundHttpException('Order not found');
        }
        return $this->render('order', ['order' => $order]);
    }
}

app/views/shopcart/_cart-item.php
<?php
/* @var $good \yii\cms\modules\shopcart\api\GoodObject */
/* @var $model \app\models\shopcart\ShopcartUpdate */

use app\helpers\CatalogHelper;
use yii\bootstrap\Html;

use app\assets\AppAsset;
$asset = AppAsset::register($this);

?>
<div class="row cart-item">
    <div class="col-lg-3 col-md-3 col-sm-3">
        <div class="item_image">
            <?=Html::a(
                Html::img(CatalogHelper::getItemThumb($good->item, $asset, 200, 200)),
                [
                    'catalog/view',
                    'category'=>$good->item->cat->slug,
                    'slug'=>$good->item->slug
                ]
            );?>
            
        </div>
    </div>

    <div class="col-lg-9 col-md-9 col-sm-9">
        <div class="item_remove pull-right">
            <?=Html::a('<i class="fa fa-times"></i>', ['shopcart/remove', 'id'=>$good->id]);?>
        </div>
        <div class="product_name">
            <?=Html::a(
                CatalogHelper::getItemTitle($good->item),
                [
                    'catalog/view',
                    'category'=>$good->item->cat->slug,
                    'slug'=>$good->item->slug
                ]
            );?>
        </div>
        <div class="item_price">
            <div class="row">
                <div class="col-sm-4">
                    <div class="price"><span class="money"><?=$good->price;?> руб.</span></div>
                </div>
                <div class="col-sm-8">
                    <div class="qty">
                        <label>
                            Кол-во:
                            <?=Html::activeTextInput($model, 'count['.$good->id.']', [
                                'value' => $good->count,
                                'class' => 'input-small form-control form-count',
                                'type' => 'number',
                                'min' => '1',
                                'data-price' => $good->item->price,
                            ]);?>
                        </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="total col-sm-12">
                    <h3>
                        Всего: 
                        <span class="money">
                            <span class="good-cost">
                                <?=($good->price*$good->count);?>
                            </span> руб.
                        </span>
                    </h3>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shopcart/_shopcart-modal.php
<?php
/* @var $model \app\models\shopcart\Shopcart */
/* @var $title string */
/* @var $id string */

use yii\bootstrap\Modal;
use yii\bootstrap\ActiveForm;
use yii\widgets\MaskedInput;
use yii\bootstrap\Html;

Modal::begin([
    'header' => '<h2 class="text-center margin-0">' . $title . '</h2>',
    'id' => 'modal-' . $id
]);

$form = ActiveForm::begin([
    'id' => 'form-' . $id,
    'action' => ['shopcart/index', 'action' => $id],
    'class' => 'shopcart-form',
]);
?>
    <?=$form->field($model, 'name')->textInput();?>
    <?=$form->field($model, 'phone')
        ->textInput()
        ->widget(MaskedInput::className(), ['mask' => '+7(999)999-99-99']);?>
    <?=$form->field($model, 'email')->textInput();?>
    <?php /*=$form->field($model, 'delivery')->dropDownList($model->getAttributeValueLabels('delivery'));?>
    <?=$form->field($model, 'city')->textInput();?>
    <?=$form->field($model, 'address')->textInput();*/?>
    <?php if($id === 'invoice'): ?>
        <?=$form->field($model, 'company')->textInput();?>
        <?=$form->field($model, 'inn')->textInput();?>
    <?php endif; ?>
    
    <?php if($id === 'payment'): ?>
        <?=$form->field($model, 'courier_name')->textInput();?>
    <?php endif; ?>

    <div class="form-group text-center">
        <?=Html::submitButton('Оформить заказ', [
            'class' => 'btn btn-primary btn-lg'
        ]);?>
    </div>
<?php
ActiveForm::end();
Modal::end();

$form_name = strtolower($model->formName());
$delivery_input_id = implode('-', [$form_name, 'delivery']);
$city_field_class = implode('-', ['field', $form_name, 'city']);
$address_field_class = implode('-', ['field', $form_name, 'address']);

$this->registerJs(<<<JS
    jQuery('#form-$id #$delivery_input_id').on('change', function(){
        var city_and_address_fields = jQuery('#form-$id .$city_field_class, #form-$id .$address_field_class');
        if(jQuery(this).val() == '1'){
            city_and_address_fields.slideDown();
        }
        else{
            city_and_address_fields.slideUp();
        }
    }).trigger('change');
JS
);
?>

app/views/shopcart/index.php
<?php
/* @var $model_update \app\models\shopcart\ShopcartUpdate */
/* @var $model_payment \app\models\shopcart\ShopcartPayment */
/* @var $model_invoice \app\models\shopcart\ShopcartInvoice */
/* @var $model_reserve \app\models\shopcart\ShopcartReserve */
/* @var $goods \yii\cms\modules\shopcart\api\GoodObject[] */

use yii\cms\modules\shopcart\api\Shopcart;
use yii\widgets\Menu;
use yii\bootstrap\Html;
use yii\bootstrap\ActiveForm;
use yii\cms\models\Setting;

$this->title = 'Корзина';
$this->params['breadcrumbs'][] = $this->title;

$goods_count = count($goods);
$payment_online = (int) Setting::findOne(['name' => 'payment_online'])->value;

?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="main_content col-sm-9 col-sm-push-3">
                <div class="cart-scope">

                    <div class="page_header">
                        <h2 class="page_heading">Ваша корзина</h2>
                    </div>

                    <?php $add_message = Yii::$app->session->getFlash('add_message'); ?>
                    <?php if (!empty($add_message)): ?>
                        <p class="alert alert-success">
                            <?=$add_message; ?>
                        </p>
                    <?php endif; ?>
                    
                    <?php if($goods_count): ?>
                        <hr>
                        <div class="cart_buttons margin-0">
                            <?php if($payment_online === 1): ?>
                            <?=Html::button("Оплатить заказ VISA | MasterCard", [
                                'class' => 'btn btn-primary btn-lg margin-r-10 margin-b-10',
                                'data-toggle' => 'modal',
                                'data-target' => '#modal-payment',
                            ]);?>
                            <?php endif; ?>

                            <?=Html::button("Выставить счет", [
                                'class' => 'btn btn-primary btn-lg margin-r-10 margin-b-10',
                                'data-toggle' => 'modal',
                                'data-target' => '#modal-invoice',
                            ]);?>

                            <?=Html::button("Зарезервировать товар", [
                                'class' => 'btn btn-primary btn-lg margin-r-10 margin-b-10',
                                'data-toggle' => 'modal',
                                'data-target' => '#modal-reserve',
                            ]);?>
                        </div>
                        <hr class="margin-t-10">
                    <?php endif; ?>
                    
                    <div class="page_content">
                        <?php if ($goods_count): ?>
                            <?php $form = ActiveForm::begin([
                                'action' => ['shopcart/index', 'action' => 'update']
                            ]); ?>
                                <div class="cart-list">
                                    <?php foreach($goods as $good): ?>
                                        <?=$this->render('_cart-item', [
                                            'good' => $good,
                                            'model' => $model_update,
                                        ]); ?>
                                    <?php endforeach; ?>
                                </div>
                                <div class="cart_subtotal">
                                    <h3>
                                        <?=Html::submitButton('Обновить корзину', [
                                            'class' => 'btn btn-alt btn-lg'
                                        ]);?>
                                        <span class="right">
                                            <span>Итого:</span>
                                            &nbsp;
                                            <span class="money">
                                                <span class="order-cost"><?=Shopcart::cost();?></span> руб.
                                            </span>
                                        </span>
                                    </h3>
                                </div>
                                <div class="cart_buttons margin-t-20 margin-b-10">
                                    
                                    <?php if($payment_online === 1): ?>
                                    <?=Html::button("Оплатить заказ VISA | MasterCard", [
                                        'class' => 'btn btn-primary btn-lg margin-r-10 margin-b-10',
                                        'data-toggle' => 'modal',
                                        'data-target' => '#modal-payment',
                                    ]);?>
                                    <?php endif; ?>

                                    <?=Html::button("Выставить счет", [
                                        'class' => 'btn btn-primary btn-lg margin-r-10 margin-b-10',
                                        'data-toggle' => 'modal',
                                        'data-target' => '#modal-invoice',
                                    ]);?>

                                    <?=Html::button("Зарезервировать товар", [
                                        'class' => 'btn btn-primary btn-lg margin-r-10 margin-b-10',
                                        'data-toggle' => 'modal',
                                        'data-target' => '#modal-reserve',
                                    ]);?>
                                    
                                </div>
                            <?php ActiveForm::end(); ?>
                        <?php else: ?>
                            <h3>На данный момент корзина пуста</h3>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <div class="sidebar col-sm-3 sidebar_left col-sm-pull-9">
                <div class="sidebar_widget sidebar_widget__collections">
                    <div class="widget_content">
                        <?=Menu::widget([
                            'items' => yii\cms\modules\menu\api\Menu::items('shopcart'),
                        ]);?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if($payment_online === 1): ?>
<?=$this->render('_shopcart-modal', [
    'title' => 'Оплатить заказ VISA | MasterCard',
    'id' => 'payment',
    'model' => $model_payment,
]);?>
<?php endif; ?>

<?=$this->render('_shopcart-modal', [
    'title' => 'Выставить счет',
    'id' => 'invoice',
    'model' => $model_invoice,
]);?>
<?=$this->render('_shopcart-modal', [
    'title' => 'Зарезервировать товар',
    'id' => 'reserve',
    'model' => $model_reserve,
]);?>
<?php

$payment_fn = $model_payment->formName();
$invoice_fn = $model_invoice->formName();
$reserve_fn = $model_reserve->formName();

$this->registerJs(<<<JS
        
    jQuery.fn.getGoodCost = function(){
        var \$this = jQuery(this);
        return parseInt(\$this.val()) * parseInt(\$this.data('price'));
    };
    
    jQuery('.form-count').on('input', function(){
        var \$this = jQuery(this),
            item = \$this.closest('.cart-item'),
            good_price_field = item.find('.good-cost'),
            order_cost_field = jQuery('.order-cost');
        
        // Выводим стоимость позиции
        good_price_field.html(\$this.getGoodCost());
        // Выводим стоимость заказа
        order_cost_field.html(countTotalCost());
        
        // Добавляем hidden-поле count во все три формы, и меняем его значение
        \$this
            .synchWith('#form-payment', '$payment_fn')
            .synchWith('#form-invoice', '$invoice_fn')
            .synchWith('#form-reserve', '$reserve_fn');
        
    }).trigger('input');
    
    function countTotalCost(){
        var cost = 0,
            inputs = jQuery('.form-count');
        
        inputs.each(function(){
            cost += jQuery(this).getGoodCost();
        });
        return cost;
    }
JS
);
?>