app/controllers/CatalogController.php
<?php

namespace app\controllers;

use app\models\CatalogFilterForm;
use Yii;
use yii\cms\modules\catalog\api\Catalog;
use yii\cms\modules\page\api\Page;
use yii\web\NotFoundHttpException;
use app\helpers\CatalogHelper;

class CatalogController extends \yii\web\Controller
{
    /**
     * Страница Каталог
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionIndex()
    {
        /*$page = Page::get('catalog');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }*/

        // Список категорий
        $cats = Catalog::cats();
        return $this->render('index', [
            //'page' => $page,
            'cats' => $cats,
        ]);
    }

    /**
     * Просмотр списка товаров в категории
     * @param string $slug Название категории
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionCat($slug){
        $model = new CatalogFilterForm();
        $cat = Catalog::cat($slug);

        if(!$cat) {
            throw new NotFoundHttpException('Категория не найдена.');
        }
        $ids = null;
        if ($model->load(Yii::$app->request->get()) && $model->validate()) {
            $ids = $model->getItemIds($cat->id);
        }
        
        return $this->render('cat', [
            'model' => $model,
            'cat' => $cat,
            'items' => $cat->getItems([
                'where' => ['id' => $ids],
                'pagination' => ['pageSize'=>16, 'pageSizeParam' => false, 'forcePageParam' => false],
                'orderBy' => 'available DESC',
            ]),
            'filter_params' => \yii\helpers\BaseJson::encode(array_filter($model->toArray())),
        ]);
    }
    
    
    public function actionAllTyres(){
        $model = new CatalogFilterForm();
        $cat_to_exclude = Catalog::cat('wheels');
        $ids = null;
        if ($model->load(Yii::$app->request->get()) && $model->validate()) {
            $ids = $model->getItemIds(null, $cat_to_exclude->id);
        }
        return $this->render('all-tyres', [
            'model' => $model,
            'items' => Catalog::items([
                'where' => ['id' => $ids],
                'pagination' => ['pageSize'=>16, 'pageSizeParam' => false, 'forcePageParam' => false],
                'orderBy' => 'available DESC',
            ]),
            'filter_params' => \yii\helpers\BaseJson::encode(array_filter($model->toArray())),
            'pagination' => Catalog::pagination(),
            'cat_to_exclude_id' => $cat_to_exclude->id,
        ]);
    }
    
    

    public function actionSearch($q){
        $page = Page::get('search');
        $q = filter_var($q, FILTER_SANITIZE_STRING);
        
        $ids = CatalogHelper::searchItemIDs($q);
        if (count($ids) == 0) {
            $where = ['id' => '0'];
        }
        else{
            $where = ['in', 'id', $ids];
        }
        
        return $this->render('search', [
            'text' => $q,
            'items' => Catalog::items([
                'pagination' => ['pageSize'=>16, 'pageSizeParam' => false, 'forcePageParam' => false],
                'where' => $where,
            ]),
            'page' => $page,
        ]);
    }

    
    public function actionView($slug){
        $item = Catalog::get($slug);
        if (!$item) {
            throw new NotFoundHttpException('Товар не найден.');
        }
        $popular = CatalogHelper::getRecommended($item);
        if(!count($popular)){
            $popular = Catalog::items([
                'pagination' => ['pageSize' => 12],
                'filters' => ['popular' => 'Да']
            ]);
        }
        return $this->render('view', [
            'item' => $item,
            'popular' => $popular,
        ]);
    }
}

app/controllers/ShopcartController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\cms\modules\catalog\api\Catalog;
use yii\cms\modules\shopcart\api\Shopcart;
use yii\web\NotFoundHttpException;


class ShopcartController extends Controller{
    
    
    public function actionIndex($action = null){
        $model_update = new \app\models\shopcart\ShopcartUpdate();
        $model_payment = new \app\models\shopcart\ShopcartPayment();
        $model_invoice = new \app\models\shopcart\ShopcartInvoice();
        $model_reserve = new \app\models\shopcart\ShopcartReserve();
        
        switch($action){
            case 'update' : $active_model = $model_update;
                break;
            case 'payment' : $active_model = $model_payment;
                break;
            case 'invoice' : $active_model = $model_invoice;
                break;
            case 'reserve' : $active_model = $model_reserve;
                break;
            default : $active_model = null;
                break;
        }
        
        if($active_model){
            if($active_model->load(Yii::$app->request->post())){
                $redirect = $active_model->action();
                if($redirect){
                    return $redirect;
                }
            }
        }
        
        return $this->render('index', [
            'goods' => Shopcart::goods(),
            'model_update' => $model_update,
            'model_payment' => $model_payment,
            'model_invoice' => $model_invoice,
            'model_reserve' => $model_reserve,
        ]);
    }
    
    
    public function actionAdd(){
        $post = Yii::$app->request->post();
        
        $item = Catalog::get($post['id']);
        if(!$item){
            throw new NotFoundHttpException('Item not found');
        }
        
        Shopcart::add($item->id, $post['count']);
        $add_message = 'Товар добавлен в корзину';
        
        if(Yii::$app->request->isAjax){
            Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            return [
                'add_message' => $add_message,
                'goods_count' => count(Shopcart::goods()),
            ];
        }
        
        Yii::$app->getSession()->setFlash('add_message', $add_message);
        return $this->redirect(['/shopcart']);
    }
    
    
    public function actionRemove($id){
        Shopcart::remove($id);
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    
    public function actionOrder($id, $token){
        $order = Shopcart::order($id);
        if(!$order || $order->access_token != $token){
            throw new NotFoundHttpException('Order not found');
        }
        return $this->render('order', ['order' => $order]);
    }
}

app/views/catalog/_carousel_item.php
<?php
/* @var $item \yii\cms\modules\catalog\api\ItemObject */

use app\helpers\CatalogHelper;
use yii\helpers\Html;
use yii\helpers\Url;

use app\assets\AppAsset;
$asset = AppAsset::register($this);

$url = Url::to(['catalog/view','category'=>$item->getCat()->slug, 'slug'=>$item->slug]);

$price = $item->getPrice();
$price_string = empty($price) ? '' : $price . ' руб.';

?>
<div class="wow product col-sm-4 col-md-3 col-lg-3 product_homepage">
    <div class="product_wrapper">
        <div class="product_img">
            <a href="<?=\yii\helpers\Url::to(['catalog/view','category'=>$item->getCat()->slug, 'slug'=>$item->slug])?>">
                <?=Html::img(CatalogHelper::getItemThumb($item, $asset)); ?>
                <?=CatalogHelper::badge($item);?>
            </a>

            <div class="product_img_hover" onclick="redirect('<?=$url;?>', event.target)">
                <?= Html::beginForm('/shopcart/add', 'post', [
                    'id'=>'cart_form_'.$item->id,
                ])?>
                    <input type="hidden" name="id" value="<?=$item->id;?>"/>
                    <input type="hidden" name="count" value="1"/>
                    <button class="btn btn-cart product-cart-btn-1" type="submit">
                        <i class="fa fa-shopping-cart"></i>
                        <span>Купить</span>
                    </button>
                <?= Html::endForm();?>
            </div>
        </div>
        <div class="product_info">
            <div class="product_name">
                <div class="product_title">
                    <a href="<?=$url;?>">
                        <?=CatalogHelper::getItemTitle($item, '')?>
                    </a>
                </div>
                <?=$this->render($item->getCat()->slug . '/_item-params.php', ['item' => $item]);?>
            </div>

            <div class="product_price ">
                <span class="money"><?=$price_string;?></span>
                <button class="btn visible-xs margin-t-5" onclick="jQuery('#cart_form_<?=$item->id;?>').trigger('submit');">
                    В корзину
                </button>
            </div>
        </div>
    </div>
</div>

app/views/catalog/_item.php
<?php
/** @var $item \yii\cms\modules\catalog\api\ItemObject */
?>
<?= $this->render('//catalog/_carousel_item', ['item' => $item]); ?>

app/views/catalog/all-tyres.php
<?php
/* @var $model \app\models\CatalogFilterForm */
/* @var $items \yii\cms\modules\catalog\api\ItemObject[] */
/* @var $filter_params array */

use yii\helpers\Url;
use yii\widgets\LinkPager;
use yii\cms\models\Setting;
use yii\widgets\ActiveForm;
use yii\bootstrap\Html;
use app\helpers\CatalogHelper;

$page_title = 'Все шины';
$this->title = $page_title;
$this->params['breadcrumbs'][] = $page_title;
$max_price = 50000;


?>


<!-- MAIN CONTENT -->
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="main_content col-sm-12">
				
					

<h2 class="page_heading"><?=$page_title;?></h2>

        



<!-- ФИЛЬТР-->
<hr>
<h3 class="text-left">Фильтр по параметрам</h3>
<?php $form = ActiveForm::begin([
    'id' => 'filter-form',
    'method' => 'get',
    'action' => '/catalog/all-tyres',
]);?>
<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <div class="checkbox">
            <?=Html::activeCheckbox($model, 'restored', [
                'onclick' => 'document.getElementById(\'filter-form\').submit();',
                'label' => '<b>'.$model->getAttributeLabel('restored').'</b>',
                'uncheck' => null,
            ]);?>
        </div>
        <div class="checkbox">
            <?=Html::activeCheckbox($model, 'used', [
                'onclick' => 'document.getElementById(\'filter-form\').submit();',
                'label' => '<b>'.$model->getAttributeLabel('used').'</b>',
                'uncheck' => null,
            ]);?>
        </div>
        <div class="checkbox">
            <?=Html::activeCheckbox($model, 'new', [
                'onclick' => 'document.getElementById(\'filter-form\').submit();',
                'label' => '<b>'.$model->getAttributeLabel('new').'</b>',
                'uncheck' => null,
            ]);?>
        </div>
    </div>
    <div class="col-lg-8 col-md-6 col-sm-6 col-xs-12 filter-container">
        <div class="filter-header text-center">
            <h4>Бренд</h4>
        </div>
        <div class="filter-body text-center">
            <?=Html::activeDropDownList($model, 'brand', CatalogHelper::getFieldVariantsInFormat('brand', $cat_to_exclude_id, '!', true), [
                'onchange' => 'document.getElementById(\'filter-form\').submit();',
                'class' => 'filter-body-select',
            ]);?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-4 col-xs-12 filter-container">
        <div class="filter-header text-center">
            <h4>Цена</h4>
        </div>
        <div class="filter-body text-center">
            <p>
                <div id="slider" class="center-block" style="width:90%;"></div>
            </p>
            <p>
                от <?=Html::activeInput('text', $model, 'price_min', ['id' => 'min-price']);?>
                до <?=Html::activeInput('text', $model, 'price_max', ['id' => 'max-price']);?>
            </p>
            <p><button type="submit" class="btn">Показать</button>
                <a href="<?=Url::to(['catalog/all-tyres']);?>">Очистить</a>
            </p>
        </div>
    </div>
    

    <div class="col-sm-8 col-xs-12">
        <div class="row">
            <div class="col-sm-6 col-xs-6 filter-container">
                <div class="filter-header text-center">
                    <h4>Ширина профиля</h4>
                </div>
                <div class="filter-body text-center">
                    <?=Html::activeDropDownList($model, 'width', CatalogHelper::getFieldVariantsInFormat('width'), [
                        'onchange' => 'document.getElementById(\'filter-form\').submit();',
                        'class' => 'filter-body-select',
                    ]);?>
                </div>
            </div>
            <div class="col-sm-6 col-xs-6 filter-container">
                <div class="filter-header text-center">
                    <h4>Высота профиля</h4>
                </div>
                <div class="filter-body text-center">
                    <?=Html::activeDropDownList($model, 'height', CatalogHelper::getFieldVariantsInFormat('height'), [
                        'onchange' => 'document.getElementById(\'filter-form\').submit();',
                        'class' => 'filter-body-select',
                    ]);?>
                </div>
            </div>
            <div class="col-sm-6 col-xs-6 filter-container">
                <div class="filter-header text-center">
                    <h4>Диаметр</h4>
                </div>
                <div class="filter-body text-center">
                    <?=Html::activeDropDownList($model, 'diameter', CatalogHelper::getFieldVariantsInFormat('diameter'), [
                        'onchange' => 'document.getElementById(\'filter-form\').submit();',
                        'class' => 'filter-body-select',
                    ]);?>
                </div>
            </div>
            <div class="col-sm-6 col-xs-6 filter-container">
                <div class="filter-header text-center">
                    <h4>Ось</h4>
                </div>
                <div class="filter-body text-center">
                    <?=Html::activeDropDownList($model, 'axle', CatalogHelper::getFieldVariantsInFormat('axle'), [
                        'onchange' => 'document.getElementById(\'filter-form\').submit();',
                        'class' => 'filter-body-select',
                    ]);?>
                </div>
            </div>
        </div>
    </div>
    
</div>
<?php ActiveForm::end(); ?>


<!-- pagination -->
<div class="product_listing_controls">
    <p class="products_count">
        <?=count($items);?> товаров из <?=$pagination->totalCount;?>
    </p>
    <?php 
        echo LinkPager::widget([
            'pagination' => $pagination,
            'options' => [
                'class' => 'pag'
            ]
        ]);
    ?>
</div>


<div>
    <!-- products listing -->
    <div class="product_listing_main row auto-clear">
    <?php foreach ($items as $item) : ?>
        <?= $this->render('_item', ['item' => $item]) ?>
    <?php endforeach; ?>
    </div>

    <!-- pagination -->
    <div class="product_listing_controls">
        <p class="products_count">
            <?=count($items);?> товаров из <?=$pagination->totalCount;?>
        </p>
        <?php 
            echo LinkPager::widget([
                'pagination' => $pagination,
                'options' => [
                    'class' => 'pag'
                ]
            ]);
        ?>
    </div>
</div>
				
            </div>
        </div>
    </div>
</div>

<?php $this->registerJs(<<<JS
    //ФИЛЬТР + ПОЛЗУНОК ФИЛЬТРА ЦЕНЫ
    var max_price = $max_price;
    var get_params = $filter_params;
    
    $('.filter-body-select').select2({
        minimumResultsForSearch: Infinity
    });

    var slider = document.getElementById('slider');
    noUiSlider.create(slider, {
        start : [10, max_price],
        connect : true,
        range : {
            min : 10,
            max : max_price
        },
        format : wNumb({
            decimals : 0
        })
    });
    var min_price_input = document.getElementById('min-price');
    var max_price_input = document.getElementById('max-price');
    slider.noUiSlider.on('update', function(values, handle){
        if(handle === 0) min_price_input.value = values[0];
        else if(handle === 1) max_price_input.value = values[1];
    });
    
    if(get_params['price_min'] && get_params['price_max']){
        slider.noUiSlider.set([
            get_params['price_min'],
            get_params['price_max']
        ]);
    }
JS
); ?>

app/views/catalog/cat.php
<?php
/* @var $model \app\models\CatalogFilterForm */
/* @var $items \yii\cms\modules\catalog\api\ItemObject[] */
/* @var $cat \yii\cms\modules\catalog\api\CategoryObject */
/* @var $filter_params array */

use yii\helpers\Url;
use yii\widgets\LinkPager;
use yii\cms\models\Setting;
use yii\widgets\ActiveForm;
use yii\bootstrap\Html;
use app\helpers\CatalogHelper;

$this->title = $cat->seo('title', $cat->model->title);
$this->params['breadcrumbs'][] = $cat->model->title;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $cat->seo('description', $cat->title)
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $cat->seo('keywords')
]);

$pagination = $cat->getPagination();
$max_price = Setting::findOne(['name' => $cat->slug . '_max_price'])->value;

?>


<!-- MAIN CONTENT -->
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="main_content col-sm-12">
				
					

<h2 class="page_heading"><?= $cat->seo('h1', $cat->title) ?></h2>

        



<!-- ФИЛЬТР-->
<hr>
<h3 class="text-left">Фильтр по параметрам</h3>

<?php $form = ActiveForm::begin([
    'id' => 'filter-form',
    'method' => 'get',
    'action' => Url::to(['catalog/cat', 'slug' => $cat->slug]),
]);?>
<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <?php if($cat->slug === 'truck-tyres'): ?>
            <div class="checkbox">
                <?=Html::activeCheckbox($model, 'restored', [
                    'onclick' => 'document.getElementById(\'filter-form\').submit();',
                    'label' => '<b>'.$model->getAttributeLabel('restored').'</b>'
                ]);?>
            </div>
            <div class="checkbox">
                <?=Html::activeCheckbox($model, 'new', [
                    'onclick' => 'document.getElementById(\'filter-form\').submit();',
                    'label' => '<b>'.$model->getAttributeLabel('new').'</b>'
                ]);?>
            </div>
        <?php endif; ?>
        <?php if(in_array($cat->slug, ['spec-tyres'])): ?>
            <div class="checkbox">
                <?=Html::activeCheckbox($model, 'used', [
                    'onclick' => 'document.getElementById(\'filter-form\').submit();',
                    'label' => '<b>'.$model->getAttributeLabel('used').'</b>'
                ]);?>
            </div>
            <div class="checkbox">
                <?=Html::activeCheckbox($model, 'new', [
                    'onclick' => 'document.getElementById(\'filter-form\').submit();',
                    'label' => '<b>'.$model->getAttributeLabel('new').'</b>'
                ]);?>
            </div>
        <?php endif; ?>
    </div>
    <div class="col-lg-8 col-md-6 col-sm-6 col-xs-12 filter-container">
        <div class="filter-header text-center">
            <h4>Бренд</h4>
        </div>
        <div class="filter-body text-center">
            <?=Html::activeDropDownList($model, 'brand', CatalogHelper::getFieldVariantsInFormat('brand', $cat->id, '', true), [
                'onchange' => 'document.getElementById(\'filter-form\').submit();',
                'class' => 'filter-body-select',
            ]);?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-4 col-xs-12 filter-container">
        <div class="filter-header text-center">
            <h4>Цена</h4>
        </div>
        <div class="filter-body text-center">
            <p>
                <div id="slider" class="center-block" style="width:90%;"></div>
            </p>
            <p>
                от <?=Html::activeInput('text', $model, 'price_min', ['id' => 'min-price']);?>
                до <?=Html::activeInput('text', $model, 'price_max', ['id' => 'max-price']);?>
            </p>
            <p><button type="submit" class="btn">Показать</button>
                <a href="<?=Url::to(['catalog/cat', 'slug' => $cat->slug]);?>">Очистить</a>
            </p>
        </div>
    </div>
    

    <div class="col-sm-8 col-xs-12">
        <div class="row">
            <?=$this->render($cat->slug . '/_filter', ['model' => $model, 'cat' => $cat]) ?>
        </div>
    </div>
    
</div>
<?php ActiveForm::end(); ?>


<!-- pagination -->
<div class="product_listing_controls">
    <p class="products_count">
        <?=count($items);?> товаров из <?=$pagination->totalCount;?>
    </p>
    <?php 
        echo LinkPager::widget([
            'pagination' => $pagination,
            'options' => [
                'class' => 'pag'
            ]
        ]);
    ?>
</div>


<div>
    <!-- products listing -->
    <div class="product_listing_main row auto-clear">
    <?php foreach ($items as $item) : ?>
        <?= $this->render('_item', ['item' => $item]) ?>
    <?php endforeach; ?>
    </div>

    <!-- pagination -->
    <div class="product_listing_controls">
        <p class="products_count">
            <?=count($items);?> товаров из <?=$pagination->totalCount;?>
        </p>
        <?php 
            echo LinkPager::widget([
                'pagination' => $pagination,
                'options' => [
                    'class' => 'pag'
                ]
            ]);
        ?>
    </div>
</div>
				
            </div>
        </div>
    </div>
</div>

<?php $this->registerJs(<<<JS
    //ФИЛЬТР + ПОЛЗУНОК ФИЛЬТРА ЦЕНЫ
    var max_price = $max_price;
    var get_params = $filter_params;
    
    $('.filter-body-select').select2({
        minimumResultsForSearch: Infinity
    });

    var slider = document.getElementById('slider');
    noUiSlider.create(slider, {
        start : [10, max_price],
        connect : true,
        range : {
            min : 10,
            max : max_price
        },
        format : wNumb({
            decimals : 0
        })
    });
    var min_price_input = document.getElementById('min-price');
    var max_price_input = document.getElementById('max-price');
    slider.noUiSlider.on('update', function(values, handle){
        if(handle === 0) min_price_input.value = values[0];
        else if(handle === 1) max_price_input.value = values[1];
    });
    
    if(get_params['price_min'] && get_params['price_max']){
        slider.noUiSlider.set([
            get_params['price_min'],
            get_params['price_max']
        ]);
    }
JS
); ?>

app/views/catalog/index.php
<?php
/* @var $page \yii\cms\modules\page\api\PageObject */

/* @var $cats \yii\cms\modules\catalog\api\CategoryObject[] */

use yii\helpers\Html;
use yii\helpers\Url;

//$this->title = $page->seo('title');
$this->title = 'Каталог';
$this->params['breadcrumbs'][] = 'Каталог';
/*$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);*/
?>

<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="main_content col-sm-12 ">
                <h2 class="page_heading">Каталог</h2>
                <div class="collection_listing_main">
                    <div class="row auto-clear">
                        
                        <?php foreach($cats as $cat): ?>
                        <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3 collection_listing_item wow">
                            <div class="collection_img">
                                <a href="<?= Url::to(['catalog/' . $cat->slug]) ?>">
                                    <?=Html::img($cat->thumb(480, 480)); ?>
                                </a>
                            </div>
                            <div class="collection_info">
                                <h4 class="collection_name">
                                    <a href="<?= Url::to(['catalog/' . $cat->slug]) ?>">
                                        <?= $cat->getTitle(); ?>
                                    </a>
                                </h4>
                                <p class="collection_products"></p>
                                <div class="collection_desc"><?= $cat->description;?></div>
                                <a class="btn" href="<?= Url::to(['catalog/' . $cat->slug]) ?>">Просмотр</a>
                            </div>
                        </div>
                        <?php endforeach; ?>
                        
                        
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>

app/views/catalog/view.php
<?php
/* @var $popular \yii\cms\modules\catalog\api\ItemObject[] */
/* @var $item \yii\cms\modules\catalog\api\ItemObject */

use app\helpers\Html;
use app\helpers\CatalogHelper;
use app\assets\AppAsset;

$asset = AppAsset::register($this);

$this->title = $item->seo('title', CatalogHelper::getItemTitle($item));
$this->params['breadcrumbs'][] = ['label' => $item->cat->title, 'url' => ['catalog/' . $item->cat->slug]];
$this->params['breadcrumbs'][] = $this->title;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $item->seo('description', Html::firstParagraph($item->description))
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $item->seo('keywords')
]);

$price = $item->getPrice();
$price_string = empty($price) ? '' : $price . ' руб.';

?>
<div class="container">
          
                
<div class="product-scope">
    <div class="product_wrap">
        <div class="row">
            
            
<div class="col-sm-6 col-lg-5 product-view">
    <div class="zoomWrapper">
        <?=Html::img(CatalogHelper::getItemThumb($item, $asset, 800, 800), ['id'=>'elevatezoom_big']); ?>
    </div>
    <?php if (count($item->photos)) : ?>
        <div id="elevatezoom_gallery">
            <a href="#" data-image="<?=$item->thumb(800, 800);?>" data-zoom-image="<?=$item->thumb(800, 800);?>">
                <?=Html::img(CatalogHelper::getItemThumb($item, $asset, 100, 100)); ?>
            </a>
            <?php foreach ($item->photos as $photo) : ?>
                <a href="#" data-image="<?=$photo->thumb(800, 800);?>" data-zoom-image="<?=$photo->thumb(800, 800);?>">
                    <?=Html::img($photo->thumb(100, 100)); ?>
                </a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>

<div class="col-sm-6 col-lg-7">
    
    <div itemprop="name" class="product_name">
        <?=CatalogHelper::getItemTitle($item)?>
    </div>
    <?=Html::beginForm(['/shopcart/add']);?>
        <div class="options clearfix">
            <div id="product_price">
                <p class="price product-price">
                    <span class="money"><?=$price_string;?></span>
                    <?=CatalogHelper::badge($item); ?>
                </p>
            </div>

            <div id="purchase">
                <label for="quantity">Кол-во: </label>
                <input min="1" type="number" id="quantity" name="count" value="1" class="form-control input-small" />
                <input type="hidden" name="id" value="<?=$item->id;?>" />
                <button class="btn btn-cart" type="submit" id="add-to-cart">Купить</button>
            </div>
        </div>
    <?=Html::endForm();?>
    <div class="product_details">
        <?=$this->render($item->getCat()->slug . '/_view-params.php', ['item'=>$item]);?>
    </div>
    
    <?php if(!empty($item->description)): ?>
    <div id="product_description" class="rte" itemprop="description">
        <h4>Описание:</h4>
        <div><?=$item->description;?></div>
    </div>
    <?php endif; ?>
</div>

            
			
        </div>
    </div>
</div>


<?php if(count($popular)): ?>
<hr>
<div class="widget_related_products">
    <h3>Рекомендуем</h3>
    <div class="widget_content">
        <div class="row product_listing_main product_listing_related auto-clear">
        <?php foreach($popular as $item): ?>
            <?= $this->render('//catalog/_carousel_item', ['item' => $item]); ?>
        <?php endforeach; ?>
        </div>
    </div>
</div>
<?php endif; ?>


</div>
<?php

$this->registerJs(<<<JS
    /* product image zoom */
    $("#elevatezoom_big").elevateZoom({
        gallery : "elevatezoom_gallery"
    });

    /* thumbs slider */
    $('#elevatezoom_gallery').bxSlider({
        responsive: true,
        infiniteLoop: false,
        pager: false,
        minSlides: 1,
        maxSlides: 3,
        moveSlides: 1,
        slideWidth: 87,
        slideMargin: 12
    });
JS
);