app/controllers/CatalogController.php
<?php

namespace app\controllers;

use app\models\CatalogFilterForm;
use Yii;
use yii\cms\modules\catalog\api\Catalog;
use yii\cms\modules\page\api\Page;
use yii\web\NotFoundHttpException;
use app\helpers\CatalogHelper;

class CatalogController extends \yii\web\Controller
{
    /**
     * Страница Каталог
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionIndex()
    {
        /*$page = Page::get('catalog');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }*/

        // Список категорий
        $cats = Catalog::cats();
        return $this->render('index', [
            //'page' => $page,
            'cats' => $cats,
        ]);
    }

    /**
     * Просмотр списка товаров в категории
     * @param string $slug Название категории
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionCat($slug){
        $model = new CatalogFilterForm();
        $cat = Catalog::cat($slug);

        if(!$cat) {
            throw new NotFoundHttpException('Категория не найдена.');
        }
        $ids = null;
        if ($model->load(Yii::$app->request->get()) && $model->validate()) {
            $ids = $model->getItemIds($cat->id);
        }
        
        return $this->render('cat', [
            'model' => $model,
            'cat' => $cat,
            'items' => $cat->getItems([
                'where' => ['id' => $ids],
                'pagination' => ['pageSize'=>16, 'pageSizeParam' => false, 'forcePageParam' => false],
                'orderBy' => 'available DESC',
            ]),
            'filter_params' => \yii\helpers\BaseJson::encode(array_filter($model->toArray())),
        ]);
    }
    
    
    public function actionAllTyres(){
        $model = new CatalogFilterForm();
        $cat_to_exclude = Catalog::cat('wheels');
        $ids = null;
        if ($model->load(Yii::$app->request->get()) && $model->validate()) {
            $ids = $model->getItemIds(null, $cat_to_exclude->id);
        }
        return $this->render('all-tyres', [
            'model' => $model,
            'items' => Catalog::items([
                'where' => ['id' => $ids],
                'pagination' => ['pageSize'=>16, 'pageSizeParam' => false, 'forcePageParam' => false],
                'orderBy' => 'available DESC',
            ]),
            'filter_params' => \yii\helpers\BaseJson::encode(array_filter($model->toArray())),
            'pagination' => Catalog::pagination(),
            'cat_to_exclude_id' => $cat_to_exclude->id,
        ]);
    }
    
    

    public function actionSearch($q){
        $page = Page::get('search');
        $q = filter_var($q, FILTER_SANITIZE_STRING);
        
        $ids = CatalogHelper::searchItemIDs($q);
        if (count($ids) == 0) {
            $where = ['id' => '0'];
        }
        else{
            $where = ['in', 'id', $ids];
        }
        
        return $this->render('search', [
            'text' => $q,
            'items' => Catalog::items([
                'pagination' => ['pageSize'=>16, 'pageSizeParam' => false, 'forcePageParam' => false],
                'where' => $where,
            ]),
            'page' => $page,
        ]);
    }

    
    public function actionView($slug){
        $item = Catalog::get($slug);
        if (!$item) {
            throw new NotFoundHttpException('Товар не найден.');
        }
        $popular = CatalogHelper::getRecommended($item);
        if(!count($popular)){
            $popular = Catalog::items([
                'pagination' => ['pageSize' => 12],
                'filters' => ['popular' => 'Да']
            ]);
        }
        return $this->render('view', [
            'item' => $item,
            'popular' => $popular,
        ]);
    }
}

app/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\helpers\CatalogHelper;
use app\models\CatalogFilterForm;
use yii\cms\models\Setting;
use yii\cms\modules\catalog\api\Catalog;
use yii\cms\modules\page\api\Page;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\cms\modules\shopcart\api\Shopcart;
use yii\helpers\Url;


class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Главная страница
     *
     * @return string
     */
    public function actionIndex(){
        $page = Page::get('index');
        $meeting_model = new \app\models\MeetingForm();
        if($meeting_model->load(Yii::$app->request->post()) && $meeting_model->action()){
            return $this->redirect(['site/message']);
        }
        $feedback_model = new \app\models\FeedbackForm();
        if($feedback_model->load(Yii::$app->request->post()) && $feedback_model->action()){
            return $this->redirect(['site/message']);
        }

        return $this->render('index', [
            'meeting_model' => $meeting_model,
            'feedback_model' => $feedback_model,
            'page' => $page,
            'catalogs' => CatalogHelper::cats(),
            'popular' => Catalog::items([
                'pagination' => ['pageSize' => 12],
                'filters' => ['popular' => 'Да']
            ]),
            'filterForm' => new CatalogFilterForm(),
            'address' => Setting::get('address'),
            'workingHours' => Setting::get('workingHours'),
            'services_cat' => \yii\cms\modules\article\api\Article::cat('services'),
        ]);
    }

    /**
     * Оформление заказа и доставка
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPayment()
    {
        $page = Page::get('payment');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('payment', [
            'page' => $page,
        ]);
    }

    /**
     * Контактная информация
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionContact()
    {
        $page = Page::get('contact');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('contact', [
            'page' => $page,
        ]);
    }

    /**
     * Цены на шиномонтаж
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPrice()
    {
        $page = Page::get('price');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('price', [
            'page' => $page,
            'map_url_1' => Setting::get('map_url_1'),
            'map_url_2' => Setting::get('map_url_2'),
            'email' => Setting::get('email'),
            'phone' => Setting::get('phone'),
            'address' => Setting::get('address'),
            'workingHours' => Setting::get('workingHours'),
        ]);
    }

    /**
     * Обмен и возврат
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionReturn()
    {
        $page = Page::get('return');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('return', [
            'page' => $page,
        ]);
    }

    /**
     * Пользовательское соглашение
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionConditions()
    {
        $page = Page::get('conditions');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('conditions', [
            'page' => $page,
        ]);
    }

    /**
     * Политика конфиденциальности
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPrivacy()
    {
        $page = Page::get('privacy');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('privacy', [
            'page' => $page,
        ]);
    }

    /**
     * Оплата заказа через эквайринг сбербанка
     *
     */
    public function actionSberbankPayment()
    {
        $order = (new Shopcart())->order;
        
        if(empty($order->id)){
            Yii::$app->session->setFlash('title', 'Ошибка: заказ не оформлен.');
            throw new NotFoundHttpException('Ваша корзина пуста. Выберите товары и оформите заказ в корзине.');
        }
        
        $cost = $order->cost;
        $returnUrl = Url::toRoute(['site/sberbank-payment-done'], 'https');
        $bundle = $this->bundleToFormat($order);
        $dataView = Yii::$app->sberbankPaymentGate->registerOrder($order->id, $cost, $bundle, $returnUrl);
        $dataView['order_id'] = $order->id;

        return $this->render('sberbank-payment', $dataView);
    }
    
    private function bundleToFormat($order){
        $result = [
            'cartItems' => ['items' => []]
        ];
        if(!empty($order->email)){
            $result['customerDetails'] = ['email' => $order->email];
        }
        $i = 0;
        foreach($order->goods as $good){
            $i++;
            $result['cartItems']['items'][] = [
                'positionId' => $i,
                'name' => CatalogHelper::getItemTitle($good->item),
                'quantity' => [
                    'value' => $good->count,
                    'measure' => 'шт',
                ],
                'itemAmount' => $good->item->price * $good->count * 100,
                'itemCode' => $good->item->id,
                /*'tax' => [
                    'taxType' => '0',
                ],*/
                'itemPrice' => $good->item->price * 100,
            ];
        }
        return $result;
    }
    
    

    /**
     * Страница, на которую редиректит эквайринг сбербанка после оплаты
     *
     * @param string $orderId ID заказа в системе платежного шлюза
     * @return mixed
     */
    public function actionSberbankPaymentDone($orderId)
    {
        $dataView = ['message' => 'Не передан ID заказа'];
        if (!empty($orderId)) {
            $dataView = Yii::$app->sberbankPaymentGate->doOrderStatusExtended($orderId);
        }

        return $this->renderPartial('_sberbank-payment-done', $dataView);
    }
    
    /**
     * Страница сообщения об удаче или ошибке
     * @return string|yii\base\Response
     */
    public function actionMessage(){
        $title = Yii::$app->session->getFlash('title');
        $message = Yii::$app->session->getFlash('message');
        $download = Yii::$app->session->getFlash('download');
        
        if(empty($message)){
            return $this->redirect(['/']);
        }
        
        return $this->render('message', [
            'title' => $title,
            'message' => $message,
            'download' => $download,
        ]);
    }
    
    /**
     * Страница скачивания файла
     * @return yii\base\Response
     * @throws NotFoundHttpException
     */
    public function actionDownload(){
        $file_to_download = Yii::$app->session->getFlash('download');
        if(!$file_to_download){
            throw new NotFoundHttpException('Страница не найдена.');
        }
        return Yii::$app->response->sendFile($file_to_download);
    }
    
    public function actionCallback(){
        $model = new \app\models\CallbackForm();
        if($model->load(Yii::$app->request->post()) && $model->action()){
            return $this->redirect(['/success']);
        }
        return $this->goBack();
    }
}

app/views/site/slides/BACKUP.php
<!--Шины для газели-->
<?php /*<div class="col-xs-3 showcase_block showcase_block__5 wow">
    <a href="<?=Url::to(['catalog/cat', 'slug' => $catalogs['gazelle-tyres']->slug]);?>">
        <?=Html::img($asset->baseUrl . '/img/showcase5.png');?>
        <div class="wrap_1">
            <div class="wrap_2">
                <div class="wrap_3">
                    <h4 class="wow"><?=$catalogs['gazelle-tyres']->title;?></h4>
                    <span class="btn wow">Подобрать</span>
                </div>
            </div>
        </div>
    </a>
</div>*/ ?>

<?php $form = ActiveForm::begin([
    'action' => Url::to(['catalog/cat', 'slug' => 'truck-tyres']),
    'method' => 'GET',
    'options' => ['class' => 'main-filter hidden-sm'],
]); ?>

    <div class="main-filter-row">
        <label for="width">Ширина</label>
        <?=Html::activeDropDownList($filterForm, 'width', getFieldVariants('width', $catalogs['truck-tyres']->id), [
            'class' => 'main-filter-select',
        ]);?>
    </div>

    <div class="main-filter-row">
        <label for="height">Высота</label>
        <?=Html::activeDropDownList($filterForm, 'height', getFieldVariants('height', $catalogs['truck-tyres']->id), [
            'class' => 'main-filter-select',
        ]);?>
    </div>

    <div class="main-filter-row">
        <label for="diameter">Диаметр</label>
        <?=Html::activeDropDownList($filterForm, 'diameter', getFieldVariants('diameter', $catalogs['truck-tyres']->id), [
            'class' => 'main-filter-select',
        ]);?>
    </div>

    <div class="main-filter-row">
        <label for="axle">Ось</label>
        <?=Html::activeDropDownList($filterForm, 'axle', getFieldVariants('axle', $catalogs['truck-tyres']->id), [
            'class' => 'main-filter-select',
        ]);?>
    </div>

    <button type="submit" class="btn">Подобрать</button>
<?php ActiveForm::end(); ?>

app/views/site/slides/_main.php
<?php
/* @var $filterForm app\models\CatalogFilterForm */
/* @var $catalogs yii\cms\modules\catalog\api\CategoryObject[] */
/* @var $address string */
/* @var $workingHours string */

use yii\bootstrap\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use app\helpers\CatalogHelper;
use yii\cms\modules\article\models\Category;
use yii\cms\modules\article\api\ArticleObject;
use app\assets\AppAsset;

$asset = AppAsset::register($this);
$slides_category = Category::find()->where(['slug' => 'main-slider'])->one();

function getFieldVariants($name, $id){
    $keys = CatalogHelper::getFieldVariants($name, $id);
    $values = array_map(function($value){
        return str_replace('.', ',', $value);
    }, $keys);
    return ['' => 'Все'] + array_combine($keys, $values);
}
?>
<div id="showcase" class="page_container">
    <div class="showcase_row__1">

        <!--ГРУЗОВЫЕ ШИНЫ-->
        <div class="table_cell table_cell__1 main-slider-wrapper" style="background-image: none;">
            <div class="main-slider">
            <?php foreach($slides_category->items as $slide): ?>
                <?php
                    $link_data = explode('|', $slide->short);
                ?>
                <div class="showcase_block__1"
                     style="
                     background-image: url(<?=(new ArticleObject($slide))->thumb(950);?>);
                     background-size: cover;
                     ">
                    <a href="<?=isset($link_data[1]) ? $link_data[1] : '#';?>"
                       <?=isset($link_data[2]) ? 'data-toggle="modal"' : '';?>>
                        <div>
                            <h2 class="wow"><?=$slide->title;?></h2>
                            <p class="wow showcase_block_description">
                                <?=str_replace(
                                    ['<p>', '</p>', '<div>', '</div>'],
                                    ['', '</br>', '', '</br>'],
                                    $slide->text
                                );?>
                            </p>
                            <p class="wow showcase_button_p">
                                <span class="btn wow animated">
                                    <?=isset($link_data[0]) ? $link_data[0] : 'Открыть';?>
                                </span>
                            </p>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
            </div>
            <?php $form = ActiveForm::begin([
                'action' => Url::to(['catalog/all-tyres']),
                'method' => 'GET',
                'options' => ['class' => 'main-filter hidden-sm hidden-xs'],
            ]); ?>

                <div class="main-filter-row">
                    <label for="width" class="main-filter-label">Ширина</label>
                    <?=Html::activeDropDownList($filterForm, 'width', getFieldVariants('width', $catalogs['truck-tyres']->id), [
                        'class' => 'main-filter-select',
                    ]);?>
                </div>

                <div class="main-filter-row">
                    <label for="height" class="main-filter-label">Высота</label>
                    <?=Html::activeDropDownList($filterForm, 'height', getFieldVariants('height', $catalogs['truck-tyres']->id), [
                        'class' => 'main-filter-select',
                    ]);?>
                </div>

                <div class="main-filter-row">
                    <label for="diameter" class="main-filter-label">Диаметр</label>
                    <?=Html::activeDropDownList($filterForm, 'diameter', getFieldVariants('diameter', $catalogs['truck-tyres']->id), [
                        'class' => 'main-filter-select',
                    ]);?>
                </div>

                <div class="main-filter-row">
                    <label for="axle" class="main-filter-label">Ось</label>
                    <?=Html::activeDropDownList($filterForm, 'axle', getFieldVariants('axle', $catalogs['truck-tyres']->id), [
                        'class' => 'main-filter-select',
                    ]);?>
                </div>
                
                <div class="main-filter-row text-center">
                    <?=Html::checkbox('used', false, ['id' => 'mf-used']);?>
                    <label for="mf-used"><?=$filterForm->getAttributeLabel('used');?></label>
                    &nbsp;&nbsp;
                    <?=Html::checkbox('restored', false, ['id' => 'mf-restored']);?>
                    <label for="mf-restored">Восст.</label>
                    <?=Html::checkbox('new', false, ['id' => 'mf-new']);?>
                    <label for="mf-new"><?=$filterForm->getAttributeLabel('new');?></label>
                </div>

                <button type="submit" class="btn">Подобрать</button>
            <?php ActiveForm::end(); ?>
        </div>
        <!--/ГРУЗОВЫЕ ШИНЫ-->
        
        <!--ШИНОМОНТАЖ-->
        <div class="table_cell table_cell__2">
            <div class="showcase_block__1 ">
                <a href="#" onclick="return false;">
                    <div>
                        <h2 class="wow" onclick="document.location='/uslugi-gruzovogo-shinomontazha';">
                            Шиномонтаж
                        </h2>
                        <p class="wow hidden-xs">
                            <?=str_replace(';', ',', $address);?>
                            <br>
                            <?=str_replace(';', '<br>', $workingHours);?>
                        </p>
                        <p>
                            <button class="btn animated" onclick="window.open('https://yandex.ru/maps/?um=constructor%3A195011201c958c24a156c14cb8cd43787734fe273589797b16e288f59bc27f6f&source=constructorLink', '_blank');">
                                Проложить маршрут
                            </button>
                            &nbsp;&nbsp;
                            <button class="btn animated" onclick="jQuery('#meeting-modal').modal('show')">
                                Записаться
                            </button>
                        </p>
                    </div>
                </a>
            </div>
        </div>
        <!--/ШИНОМОНТАЖ-->
    </div>

    <div class="clearfix"></div>

    <div class="showcase_row__2">
        <div class="row">


        <!--ГРУЗОВЫЕ ШИНЫ-->
        <div class="col-xs-3 showcase_block showcase_block__3 wow">
            <a href="<?=Url::to(['catalog/cat', 'slug' => $catalogs['truck-tyres']->slug]);?>">
                <?=Html::img($asset->baseUrl . '/img/showcase2.png');?>
                <div class="wrap_1">
                    <div class="wrap_2">
                        <div class="wrap_3">
                            <h4 class="wow"><?=$catalogs['truck-tyres']->title;?></h4>
                            <span class="btn wow">Подобрать</span>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!--/ГРУЗОВЫЕ ШИНЫ-->
        
        <!--ДИСКИ-->
        <div class="col-xs-3 showcase_block showcase_block__2 wow">
            <a href="<?=Url::to(['catalog/cat', 'slug' => $catalogs['wheels']->slug]);?>">
                <?=Html::img($asset->baseUrl . '/img/showcase4.png');?>
                <div class="wrap_1">
                    <div class="wrap_2">
                        <div class="wrap_3">
                            <h4 class="wow"><?=$catalogs['wheels']->title;?></h4>
                            <span class="btn wow">Подобрать</span>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!--/ДИСКИ-->

        <!--ЛЕГКОВЫЕ ШИНЫ-->
        <div class="col-xs-3 showcase_block showcase_block__4 wow">
            <a href="<?=Url::to(['catalog/cat', 'slug' => $catalogs['auto-tyres']->slug]);?>">
                <?=Html::img($asset->baseUrl . '/img/showcase3.png');?>
                <div class="wrap_1">
                    <div class="wrap_2">
                        <div class="wrap_3">
                            <h4 class="wow"><?=$catalogs['auto-tyres']->title;?></h4>
                            <span class="btn wow">Подобрать</span>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!--/ЛЕГКОВЫЕ ШИНЫ-->

        
        
        <div class="col-xs-3 showcase_block showcase_block__5 wow">
            <a href="<?=Url::to(['catalog/cat', 'slug' => $catalogs['truck-tyres']->slug, 'restored' => '1']);?>">
                <?=Html::img($asset->baseUrl . '/img/showcase5.png');?>
                <div class="wrap_1">
                    <div class="wrap_2">
                        <div class="wrap_3">
                            <h4 class="wow">Восстановленные шины</h4>
                            <span class="btn wow">Подобрать</span>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!--/Шины для газели-->

        </div>
    </div>
</div>

<?php
$this->registerJs(<<<JS
    jQuery('.main-slider').bxSlider({
        oneToOneTouch : false,
        pager : false,
        auto : true,
        pause : 5000,
        speed : 1000,
        useCSS : false,
        stopAutoOnClick : true
    });
JS
);
?>
<?=$this->render('//layouts/modals/_meeting-modal', [
    'model' => $meeting_model,
]);?>
<?=$this->render('//layouts/modals/_feedback-modal', [
    'model' => $feedback_model,
]);?>

app/views/site/slides/_map.php
<?php 
/* @var $address string Адрес в формате Адрес,place_id,latitude,longitude */ 

use yii\cms\models\Setting; 

?> 

<?php 
$parts = explode("#", $address); 
if (count($parts) == 4): ?> 
    <div>
        <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A195011201c958c24a156c14cb8cd43787734fe273589797b16e288f59bc27f6f&amp;width=100%25&amp;height=480&amp;lang=ru_RU&amp;scroll=false"></script>
    </div>
<?php endif; ?> 

app/views/site/slides/_popular.php
<?php
/* @var $popular \yii\cms\modules\catalog\api\ItemObject[] */
?>
<div id="main" role="main">
    <div class="container">
        <div class="featured_products">
            <h2 class="page_heading">Популярные товары</h2>
            <div class="product_listing_main">
                <div class="row auto-clear">
                    <?php foreach($popular as $item): ?>
                        <?=$this->render('//catalog/_carousel_item', ['item' => $item]); ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>