app/controllers/ServicesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\cms\modules\article\api\Article;


class ServicesController extends Controller{
    
    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionView($slug){
        $cat = Article::cat('services');
        if(!$cat){
            throw new NotFoundHttpException('Категория не найдена.');
        }
        $article = Article::get($slug);
        if(!$article){
            throw new NotFoundHttpException('Статья не найдена.');
        }
        $model = new \app\models\ServicesForm();
        $model->service = $article->title;
        if($model->load(Yii::$app->request->post()) && $model->action()){
            return $this->redirect(['/success']);
        }
        $price_model = new \app\models\ServicesPriceForm();
        $price_model->service = $article->title;
        if($price_model->load(Yii::$app->request->post()) && $price_model->action($article)){
            return $this->redirect(['/success']);
        }
        return $this->render('view', [
            'article' => $article,
            'cat' => $cat,
            'model' => $model,
            'price_model' => $price_model,
        ]);
    }
    
    public function actionIndex(){
        $cat = Article::cat('services');
        if(!$cat){
            throw new NotFoundHttpException('Категория не найдена.');
        }
        return $this->render('index', [
            'cat' => $cat,
        ]);
    }
    
    public function actionDownloadPrice($slug){
        $article = Article::get($slug);
        if(!$article){
            throw new NotFoundHttpException('Статья не найдена.');
        }
        $file = Yii::getAlias('@webroot') . '/uploads/' . $article->model->file;
        if(!file_exists($file) || !is_file($file)){
            throw new NotFoundHttpException('Файл не найден.');
        }
        return Yii::$app->response->sendFile($file);
    }
}

app/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\helpers\CatalogHelper;
use app\models\CatalogFilterForm;
use yii\cms\models\Setting;
use yii\cms\modules\catalog\api\Catalog;
use yii\cms\modules\page\api\Page;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\cms\modules\shopcart\api\Shopcart;
use yii\helpers\Url;


class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Главная страница
     *
     * @return string
     */
    public function actionIndex(){
        $page = Page::get('index');
        $meeting_model = new \app\models\MeetingForm();
        if($meeting_model->load(Yii::$app->request->post()) && $meeting_model->action()){
            return $this->redirect(['site/message']);
        }
        $feedback_model = new \app\models\FeedbackForm();
        if($feedback_model->load(Yii::$app->request->post()) && $feedback_model->action()){
            return $this->redirect(['site/message']);
        }

        return $this->render('index', [
            'meeting_model' => $meeting_model,
            'feedback_model' => $feedback_model,
            'page' => $page,
            'catalogs' => CatalogHelper::cats(),
            'popular' => Catalog::items([
                'pagination' => ['pageSize' => 12],
                'filters' => ['popular' => 'Да']
            ]),
            'filterForm' => new CatalogFilterForm(),
            'address' => Setting::get('address'),
            'workingHours' => Setting::get('workingHours'),
            'services_cat' => \yii\cms\modules\article\api\Article::cat('services'),
        ]);
    }

    /**
     * Оформление заказа и доставка
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPayment()
    {
        $page = Page::get('payment');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('payment', [
            'page' => $page,
        ]);
    }

    /**
     * Контактная информация
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionContact()
    {
        $page = Page::get('contact');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('contact', [
            'page' => $page,
        ]);
    }

    /**
     * Цены на шиномонтаж
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPrice()
    {
        $page = Page::get('price');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('price', [
            'page' => $page,
            'map_url_1' => Setting::get('map_url_1'),
            'map_url_2' => Setting::get('map_url_2'),
            'email' => Setting::get('email'),
            'phone' => Setting::get('phone'),
            'address' => Setting::get('address'),
            'workingHours' => Setting::get('workingHours'),
        ]);
    }

    /**
     * Обмен и возврат
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionReturn()
    {
        $page = Page::get('return');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('return', [
            'page' => $page,
        ]);
    }

    /**
     * Пользовательское соглашение
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionConditions()
    {
        $page = Page::get('conditions');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('conditions', [
            'page' => $page,
        ]);
    }

    /**
     * Политика конфиденциальности
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPrivacy()
    {
        $page = Page::get('privacy');
        if (!$page) {
            throw new NotFoundHttpException('Item not found.');
        }
        return $this->render('privacy', [
            'page' => $page,
        ]);
    }

    /**
     * Оплата заказа через эквайринг сбербанка
     *
     */
    public function actionSberbankPayment()
    {
        $order = (new Shopcart())->order;
        
        if(empty($order->id)){
            Yii::$app->session->setFlash('title', 'Ошибка: заказ не оформлен.');
            throw new NotFoundHttpException('Ваша корзина пуста. Выберите товары и оформите заказ в корзине.');
        }
        
        $cost = $order->cost;
        $returnUrl = Url::toRoute(['site/sberbank-payment-done'], 'https');
        $bundle = $this->bundleToFormat($order);
        $dataView = Yii::$app->sberbankPaymentGate->registerOrder($order->id, $cost, $bundle, $returnUrl);
        $dataView['order_id'] = $order->id;

        return $this->render('sberbank-payment', $dataView);
    }
    
    private function bundleToFormat($order){
        $result = [
            'cartItems' => ['items' => []]
        ];
        if(!empty($order->email)){
            $result['customerDetails'] = ['email' => $order->email];
        }
        $i = 0;
        foreach($order->goods as $good){
            $i++;
            $result['cartItems']['items'][] = [
                'positionId' => $i,
                'name' => CatalogHelper::getItemTitle($good->item),
                'quantity' => [
                    'value' => $good->count,
                    'measure' => 'шт',
                ],
                'itemAmount' => $good->item->price * $good->count * 100,
                'itemCode' => $good->item->id,
                /*'tax' => [
                    'taxType' => '0',
                ],*/
                'itemPrice' => $good->item->price * 100,
            ];
        }
        return $result;
    }
    
    

    /**
     * Страница, на которую редиректит эквайринг сбербанка после оплаты
     *
     * @param string $orderId ID заказа в системе платежного шлюза
     * @return mixed
     */
    public function actionSberbankPaymentDone($orderId)
    {
        $dataView = ['message' => 'Не передан ID заказа'];
        if (!empty($orderId)) {
            $dataView = Yii::$app->sberbankPaymentGate->doOrderStatusExtended($orderId);
        }

        return $this->renderPartial('_sberbank-payment-done', $dataView);
    }
    
    /**
     * Страница сообщения об удаче или ошибке
     * @return string|yii\base\Response
     */
    public function actionMessage(){
        $title = Yii::$app->session->getFlash('title');
        $message = Yii::$app->session->getFlash('message');
        $download = Yii::$app->session->getFlash('download');
        
        if(empty($message)){
            return $this->redirect(['/']);
        }
        
        return $this->render('message', [
            'title' => $title,
            'message' => $message,
            'download' => $download,
        ]);
    }
    
    /**
     * Страница скачивания файла
     * @return yii\base\Response
     * @throws NotFoundHttpException
     */
    public function actionDownload(){
        $file_to_download = Yii::$app->session->getFlash('download');
        if(!$file_to_download){
            throw new NotFoundHttpException('Страница не найдена.');
        }
        return Yii::$app->response->sendFile($file_to_download);
    }
    
    public function actionCallback(){
        $model = new \app\models\CallbackForm();
        if($model->load(Yii::$app->request->post()) && $model->action()){
            return $this->redirect(['/success']);
        }
        return $this->goBack();
    }
}

app/views/site/_sberbank-payment-done.php
<p><?=$message;?></p>

app/views/site/conditions.php
<?php
/** @var $page \yii\cms\modules\page\api\PageObject */

use yii\helpers\Html;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title', $page->title);
$this->params['breadcrumbs'][] = $page->title;

?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="page_heading"><?=Html::encode($this->title);?></h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="main_content col-sm-12">
                <?=$page->getText() ?>
            </div>
        </div>
    </div>
</div>

app/views/site/contact.php
<?php
/* @var $page \yii\cms\modules\page\api\PageObject */

use yii\bootstrap\Html;
use yii\cms\models\Setting;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title', $page->title);
$this->params['breadcrumbs'][] = $page->title;

?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="page_heading"><?=Html::encode($this->title);?></h2>
                <hr>
            </div>
        </div>
	<div class="row">
            <div class="col-sm-6">
                <?=$this->render('slides/_map', ['address' => $page->address]); ?>
            </div>
            <div class="main_content col-sm-6">
		<div class="contact-scope">
                    <div class="contact-socials">
                        <p><strong>Мы в соц-сетях:</strong></p>
                        <p>
                            <?=Html::a('', Setting::get('social_vk'), [
                                'class' => 'fa fa-vk',
                                'target' => '_blank',
                            ]);?>
                            <?=Html::a('', Setting::get('social_facebook'), [
                                'class' => 'fa fa-facebook',
                                'target' => '_blank',
                            ]);?>
                            <?=Html::a('', Setting::get('social_instagram'), [
                                'class' => 'fa fa-instagram',
                                'target' => '_blank',
                            ]);?>
                        </p>
                    </div>
                    <?=$page->getText() ?>
                </div>
            </div>
	</div>
    </div>
</div>

app/views/site/error.php
<?php
use yii\helpers\Html;

$title = Yii::$app->session->getFlash('title');

$this->title = !empty($title) ? $title : $name;
$this->params['no_map'] = true;

?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="main_content col-sm-12 text-center">
                <h1 class="page_heading"><?= Html::encode($this->title) ?></h1>
                <hr>
                <h2>
                    <?= nl2br(Html::encode($message)) ?>
                </h2>
            </div>
        </div>
    </div>
</div>

app/views/site/feedback.php
<?php
/** @var $page \yii\cms\modules\page\api\PageObject */
/** @var $login_form app\modules\customer\models\LoginForm */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = $page->seo('title', $page->title);
$this->params['breadcrumbs'][] = $page->title;

?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="page_heading"><?=Html::encode($this->title);?></h2>
                <hr>
            </div>
        </div>

        <?php if($result): ?>
            <div class="row">
                <div class="main_content col-sm-12">
                    <h4>Спасибо что оставили заявку!</h4>
                    <p> Наш менеджер свяжится с вами в кротчайшие сроки.</p>
                </div>
            </div>
        <?php else: ?>
            <div class="row">
                <div class="main_content col-sm-12">
                    <?php $form = ActiveForm::begin([
                        'id' => 'feedback-form',
                        'options' => ['class' => 'center-block'],
                    ]); ?>

                    <?php if(!empty($feedbackForm->getErrors())): ?>
                        <div class="has-error">
                            <div class="help-block"><?= $form->errorSummary($feedbackForm);?></div>
                        </div>
                    <?php endif;?>

                    <?=$form->field($feedbackForm, 'name');?>
                    <?=$form->field($feedbackForm, 'email');?>
                    <?=$form->field($feedbackForm, 'phone')?>
                    <?=$form->field($feedbackForm, 'text') ->textarea(['rows' => 6])?>

                    <div class="form-group text-center">
                        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        <?php endif;?>
    </div>
</div>

app/views/site/index.php
<?php
/* @var $catalogs yii\cms\modules\catalog\api\CategoryObject[] */
/* @var $page \yii\cms\modules\page\api\PageObject */
/* @var $popular \yii\cms\modules\catalog\api\ItemObject[] */
/* @var $filterForm app\models\CatalogFilterForm */
/* @var $address string */
/* @var $workingHours string */
/* @var $services_cat \yii\cms\modules\article\api\CategoryObject */

use yii\helpers\Url;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title', $page->title);
$this->params['breadcrumbs'][] = $page->title;
$this->params['no_breadcrumbs'] = true;
?>
<!-- Первый слайд -->
<?= $this->render('slides/_main', [
    'meeting_model' => $meeting_model,
    'feedback_model' => $feedback_model,
    'filterForm' => $filterForm,
    'catalogs' => $catalogs,
    'address' => $address,
    'workingHours' => $workingHours,
]); ?>

<!-- Популярные товары -->
<?= $this->render('slides/_popular', ['popular' => $popular]); ?>

<!-- HOMEPAGE INFO BLOCK -->
<div id="parallax_block" class="homepage_info page_container">
    <div class="container">
        <h2 id="homepage_info__title">
            <span class="wrap-1 wow">Наши услуги</span>
        </h2>

        <div class="row auto-clear margin-t-40">
            <?php foreach($services_cat->items as $service):  ?>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 homepage_info_item wow services-item">
                <h3 class="wow">
                    <a href="<?=Url::toRoute(['services/view', 'slug' => $service->slug]);?>">
                        <?=$service->title;?>
                    </a>
                </h3>
                <p class="wow"><?=strip_tags($service->short);?></p>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<!-- Карта -->
<div class="container"> 
    <div class="row"> 
        <div class="col-sm-12 map-container"> 
            <?= $this->render('slides/_map', ['address' => $page->address]); ?>
        </div> 
    </div> 
</div>

app/views/site/message.php
<?php
/* @var $title string */
/* @var $message string */
/* @var $download string */

use yii\bootstrap\Html;
$this->title = $title;
$this->params['no_map'] = true;

if(!empty($download)){
    Yii::$app->session->setFlash('download', $download);
    $this->registerJs(
<<<JS
    document.location = '/download';
JS
    );
}

?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="main_content col-sm-12 text-center">
                <h1 class="page_heading"><?= Html::encode($title) ?></h1>
                <hr>
                <h2>
                    <?= nl2br(Html::encode($message)) ?>
                </h2>
                <div class="text-center">
                    <?=Html::a('На главную', ['/'], ['class' => 'btn btn-primary btn-lg']);?>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/site/payment.php
<?php 
/** @var $page \yii\cms\modules\page\api\PageObject */

use yii\helpers\Html;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title', $page->title);
$this->params['breadcrumbs'][] = $page->title;

?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="page_heading"><?=Html::encode($this->title);?></h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="main_content col-sm-8">
                <?=$page->getText() ?>
            </div>
        </div>
    </div>
</div>
             

app/views/site/price.php
<?php 
/* @var $page \yii\cms\modules\page\api\PageObject */
/* @var $map_url_1 string */
/* @var $map_url_2 string */
/* @var $email string */
/* @var $phone string */
/* @var $address string */
/* @var $workingHours string */

use yii\cms\models\Setting;
use yii\helpers\Html;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title', $page->title);
$this->params['breadcrumbs'][] = $page->title;
?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="page_heading"><?=Html::encode($this->title);?></h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <h4>Адрес</h4>
                <ul>
                    <li><?=str_replace(';', '<br>', $address);?></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <h4>Время работы</h4>
                <ul>
                    <li><?=str_replace(';', '<br>', $workingHours);?></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <h4>Схемы маршрута</h4>
                <ul>
                    <li><a href="<?=$map_url_1;?>" target="_blank">Схема проезда по М4 на Москву</a></li>
                    <li><a href="<?=$map_url_2;?>" target="_blank">Схема проезда по М4 на Краснодар</a></li>
                </ul>
            </div>
            <div class="col-sm-3">
                <h4>Контакты</h4>
                <ul>
                    <li>тел.: <a href="tel:<?=preg_replace('/[^\d+]/', '', $phone);?>"><?=$phone;?></a></li>
                    <li>e-mail: <a href="mailto:<?=$email?>"><?=$email?></a></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="main_content col-sm-12">
                <?=$page->getText() ?>
            </div>
        </div>
    </div>
</div>
             

app/views/site/privacy.php
<?php
/** @var $page \yii\cms\modules\page\api\PageObject */

use yii\helpers\Html;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title', $page->title);
$this->params['breadcrumbs'][] = $page->title;
?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="page_heading"><?=Html::encode($this->title);?></h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="main_content col-sm-12">
                <?=$page->getText() ?>
            </div>
        </div>
    </div>
</div>

app/views/site/report_html.php
<?php
use app\helpers\CatalogHelper;
?>
<table cellpadding="10">
    <tr>
        <td>Номер заказа: </td>
        <td><b><?=$order->id;?></b></td>
    </tr>

<?php foreach($order->goods as $good): ?>
    <tr>
        <td colspan="2">
            Наименование: <i><?=CatalogHelper::getItemTitle($good->item);?></i><br>
    
            За единицу: <b><?=$good->item->price;?> руб.</b><br>
            
            Кол-во: <b><?=$good->count;?></b>
        </td>
    </tr>
<?php endforeach; ?>   
    
    <tr>
        <td>Сумма заказа: </td>
        <td><b><?=$order->cost;?> руб.</b></td>
    </tr>
</table>

<br><br>

<table cellpadding="10">
<?php foreach($data as $key => $value): ?>
    <tr>
        <td><?=$key;?>:</td>
        <td><b><?=$value;?></b></td>
    </tr>
<?php endforeach; ?>
</table>

app/views/site/report_text.php
<?php
use app\helpers\CatalogHelper;
?>
Номер заказа: <?=$order->id;?>

<?php foreach($order->goods as $good): ?>
    Наименование: <?=CatalogHelper::getItemTitle($good->item);?>

    За единицу: <?=$good->item->price;?> руб.

    Кол-во: <?=$good->count;?>

<?php endforeach; ?>   

Сумма заказа: <?=$order->cost;?> руб.

    
<?php foreach($data as $key => $value): ?>
    <?=$key;?> : <?=$value;?>

<?php endforeach; ?>

app/views/site/return.php
<?php
/** @var $page \yii\cms\modules\page\api\PageObject */

use yii\helpers\Html;

$this->registerMetaTag([
    'name' => 'description',
    'content' => $page->seo('description')
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $page->seo('keywords')
]);
$this->title = $page->seo('title', $page->title);
$this->params['breadcrumbs'][] = $page->title;
?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="page_heading"><?=Html::encode($this->title);?></h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="main_content col-sm-12">
                <?=$page->getText() ?>
            </div>
        </div>
    </div>
</div>

app/views/site/sberbank-payment.php
<?php
use yii\helpers\Html;

$this->title = "Оплата заказа №{$order_id} через платёжный шлюз Сбербанка";
$this->registerJs(<<<JS
    var iframe = document.getElementsByTagName('iframe')[0];
    iframe.onload = function(){
            $([document.documentElement, document.body]).animate({
            scrollTop: $("body").offset().top + 120
        }, 300);
    };
JS
);
?>
<div id="main" role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2 class="page_heading"><?=Html::encode($this->title);?></h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="main_content col-sm-8">
                <?php if (empty($formUrl)) : ?>
                    <p><?=$message;?></p>
                <?php else: ?>
                    <iframe src="<?=$formUrl;?>" width="600" height="1000"></iframe>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>